# Generated by Django 2.1.1 on 2018-10-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=50)),
                ('gender', models.BooleanField()),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
            ],
        ),
    ]
